print('+________________________________________________________________+')
print('|                                                5/12/2023       |')
print('|Dear lokesh                                                     |')
print('|    Here I am enjoying learning.                                |')
print('|Learn how to create websites and games.                         |')
print('|Dont be Lazy                                                    |')
print('|                                           ❤❤💖               |')
print('|                                       Thank You                |')
print('|________________________________________________________________|')